#!/usr/bin/python

from bs4 import BeautifulSoup
import requests
import sys
import os
import argparse

def get_complex_name(target):
    result = ""
    for child in target.children:
        if child.string is not None:
            result += child.string
    return result

def indent():
    return '\t' * tabs

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--defaultName', help='use default name and don\'t ask for a new one', action='store_true')
parser.add_argument('-l', '--link', help='give link to script directly')
parser.add_argument('-n', '--name', help='give name to script directly')
args = parser.parse_args()


website_prefix = 'https://developer.apple.com/documentation/uikit/'
if args.link:
    website = args.link
else:
    website = input('Website to scrape: {0}'.format(website_prefix))

html = requests.get(website_prefix + website)
soup = BeautifulSoup(html.text, 'html.parser')
    
topics = soup.find('div', class_='contenttable-container row')
allCases = []
for code in topics('code', class_='display-name'):
    identifier = code.find('span', class_='identifier')
    if identifier.previous_sibling.text == 'case ':
        allCases += [identifier.text]
        
if allCases == []:
    print('Error: Couldn\'t find any cases.')
    sys.exit()

original_name = get_complex_name(soup.h1.span)
if args.name:
    name = args.name
else:
    if original_name.startswith('UI'):
        name = original_name[2:]
    else:
        name = original_name

    if not args.defaultName:
        input = input('If you want to use different name than {0}, enter it now (or press Enter to keep this one): '.format(name))
        if input is not '':
            name = input

path = 'Enums/{0}.swift'.format(name)
os.makedirs(os.path.dirname(path), exist_ok=True)
        
file = open(path, 'w')
file.write(u'//This enum was generated by a Python script made by Matyáš Kříž\n\n')
file.write('import Foundation\n\n')
file.write('public enum {0}: String {{\n'.format(name))
tabs = 1

for case in allCases:
    file.write(indent() + 'case {0}\n'.format(case))

file.write('}\n\n')
tabs -= 1

file.write('#if ReactantRuntime\n')
tabs += 1
file.write(indent() + 'import UIKit\n\n')

file.write(indent() + 'extension {0}: Applicable {{\n\n'.format(name))
tabs += 1

file.write(indent() + 'public var value: Any? {\n')
tabs += 1

file.write(indent() + 'switch self {\n')
for case in allCases:
    file.write(indent() + 'case .{0}:\n'.format(case))
    file.write(indent() + '\t' + 'return {0}.{1}.rawValue\n'.format(original_name, case.replace('`', '')))
file.write(indent() + '}\n')
tabs -= 1

file.write(indent() + '}\n')
tabs-= 1

file.write(indent() + '}\n')
tabs -= 1
file.write('#endif\n')

file.close()